### PR TITLE
SUOSERIAL (SUOUART & SUOUSB) Demonstration Example

### PR DESCRIPTION
**Pull request by ioannis-karachalios**
This application should replace the `suouart` and `suousb` demonstration examples. A new interface namely `suoserial` is introduced and features multiple peripheral interfaces that can be used for alternative firmware update mechanisms.

### CODE REVIEW

**Comment by ioannis-karachalios** [comment]
@koen-vdm can you please elaborate on the CI report? It's not clear to me why the CI fails to find the project.

**Comment by koen-vdm** [comment]
Hello @ioannis-karachalios,
In the [logs](https://github.com/dialog-semiconductor/BLE_SDK10_examples/actions/runs/9748179373/job/26902612329), I cannot find a build config named DA1469x-00-Debug_QSPI for project suoserial_sample_code. this is what the CI looks for when determining if the build succeeded.

**Comment by ioannis-karachalios** [comment]
@koen-vdm, in contrast to most of the examples, this one can be built for different interfaces e.g. `DA1469x-00-Release_QSPI-SUOUSB` or `DA1469x-00-Release_QSPI-SUOUART`. Is there any way to overcome this peculiarity?

**Comment by koen-vdm** [comment]
@ioannis-karachalios, 
No unfortunately the build configuration is hardcoded in the CI. Could you define the SUOUART and SUOUSB using #defines in the code instead? and provide instructions in the readme.md how to switch between configurations.

**Comment by ioannis-karachalios** [comment]
@koen-vdm, that did the trick! Instead of providing multiple build rules out of the box, users should now explicitly select an interface of interest by declaring the corresponding macro in customer's configuration file.

**Comment by ioannis-karachalios** [comment]
This PR should first be handled internally.

**Pull request closed without merging**
